### ISSUE TITLE
separate out four types in simulations for interactive plot

### ISSUE THREAD

**Issue by wkvong** [alexatartaglini/alcove#12]

**Comment by alexatartaglini** [comment]
Just to clarify, we want the four types to be in their own cells in the same notebook?

**Comment by wkvong** [comment]
yes, that's right! so when you run the code for each cell it should only produce the interactive plot for that particular combination of model type (mlp vs. alcove) and feature type (abstract vs. images)

**Comment by alexatartaglini** [comment]
Ok, awesome! I've done that. Just separating them didn't fix the weird problem on its own though.
