### ISSUE TITLE
only train the model for the max number of epochs, rather than a varying number of epochs

### ISSUE THREAD

**Issue by wkvong** [alexatartaglini/alcove#15]
I realised that there's no need to train the same model for (32/64/128) epochs etc. if everything else is constant, instead we can train only for the maximum number of epochs (128), and then take the subset of trials for the more limited conditions

**Comment by wkvong** [comment]
additionally, right now it seems like the simulations are saving results at every 5 epochs, is it straightforward to save results at every epoch instead?

**Comment by alexatartaglini** [comment]
From now on, the simulations will run with 128 epochs by default, and the CSVs will store results for each epoch (although you can still specify/change these things!). I'm going to have to rerun the simulations that we've already done, so I'll upload those CSVs in a little bit.
